name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[pages]
publish_dir = "dist" # 根据你的项目结构调整 publish_dir

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "tempfile.zhencheng.win"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "87bd84df2e494b89b41342b727ccddca"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://tempfile.zhencheng.win"

# url to repo, displayed in the index page
REPO = "https://github.com/SharzyL/pastebin-worker"

# url to the favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "Sharzy"

# the email displayed in TOS
TOS_MAIL = "pb@shz.al"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600

[vars.BASIC_AUTH]
user1 = "987654"
